### ISSUE TITLE
.cpu() operation as bottleneck in training

### ISSUE THREAD

**Issue by tadbeer** [ybarancan/STSU#11]
The **.cpu()** operation used in Hungarian matching, to bring tensor to cpu for _linear-sum-assignment_ , takes a significant amount of time, as compared to the entire forward pass. Is there a specific method of it's usage, which (possibly) handles it's time consumption?
I am using Hungarian matching in one of my work, and using the **.cpu()** operation has significantly increased the training time.

**Comment by ybarancan** [comment]
Hi,
In the matcher.py (which is mostly taken from DETR-Facebook), the Hungarian matching is done through scipy library. This requires, as far as I know, CPU tensors. In order to avoid moving tensors to CPU, a CUDA library for Hungarian matching can be used. 
Best
