### ISSUE TITLE
vis error

### ISSUE THREAD

**Issue by sumenpuyuan** [ybarancan/STSU#12]
![image](https://user-images.githubusercontent.com/14249563/215313445-cf61f429-63ab-412b-8273-bd2e167b9e99.png)
![image](https://user-images.githubusercontent.com/14249563/215313455-d609dcfe-0f02-4373-b9e1-df7cd643c6cb.png)
Using the transformer model, the above is gt, and the bottom is the prediction, the results seem to have a large gap

**Comment by ybarancan** [comment]
This is very weird. Have you observed this for one sample or does it happen frequently? By the way, the prediction shown here is before merging step. So can you also show the merged lane graph?

**Comment by sumenpuyuan** [comment]
I downloaded the complete nuscenes dataset and it turned out to be only for intersections, and his visualizations are all poor
transformer model
__gt_coef_visible_all_roads.jpg
![image](https://user-images.githubusercontent.com/14249563/218716519-22b0c689-93eb-458c-a9ca-582530043099.png)
__merged_road.jpg
![image](https://user-images.githubusercontent.com/14249563/218716627-e3100457-8cd8-4ea7-8f53-de808d94a014.png)

**Comment by ybarancan** [comment]
Hi,
Do the quantitative results match the paper? If so, this actually looks like a plausbile estimate of the network. In complicated scenes with possibly occlusions (a lot of cars, rain/ fog etc.) the visual performance drops significantly.

**Comment by sumenpuyuan** [comment]
my result is as follows

ERROR:root:mean_recall : 0.546578436628684
ERROR:root:mean_pre : 0.606558468340185
ERROR:root:mean_f_score : 0.5745103166217702
ERROR:root:mse : nan
ERROR:root:assoc_iou : 0.3993424771500831
ERROR:root:assoc_precision : 0.6007536357529056
ERROR:root:assoc_recall : 0.543614038222957
ERROR:root:assoc_f : 0.5702589960045314
ERROR:root:matched_gt : 36567
ERROR:root:unmatched_gt : 23803
ERROR:root:detection_ratio : 0.6057147489528781

**Comment by ybarancan** [comment]
The results are correct.
