### ISSUE TITLE
Missing File  'zoom_sampling_dict.npy'

### ISSUE THREAD

**Issue by linxcan** [ybarancan/STSU#13]
Hello, thank you for your work. When we reproduced, we found that the file  'zoom_sampling_dict.npy' was missing. How should I get this file? Thanks for taking the time to answer our questions.
![image](https://user-images.githubusercontent.com/91445884/220805333-87cbba50-f740-44de-8c14-3cc6a777a31e.png)

**Comment by tuntun-sd** [comment]
To get the zoom_sampling_dict.npy, needing to run src/data/nuscenes/sampling_grid_maker.py (Set the path to save the .npy file in the sampling_grid_maker.py)
However, when I run it, I met this problem below:
> AttributeError: 'dict' object has no attribute 'item'

Maybe you will face the same problem. To solve this, could change the reference function of 'dict' as follow:
```
for loc in intrinsic_dict.keys():
    print(loc)
    print(intrinsic_dict.get(loc))
    print(camera_matrix_dict.get(loc)[:3,-1])
    my_list = []
    for k in augment_steps:
        write_row, write_col, total_mask = nusc_utils.zoom_augment_grids((900,1600,3),intrinsic_dict.get(loc),
                                                                                 camera_matrix_dict.get(loc)[:3,-1], k)
```
