### ISSUE TITLE
Transformer training with Nuscenes

### ISSUE THREAD

**Issue by jiaoL06** [ybarancan/STSU#16]
As for the Transformer training with Nuscenes datasets, How long does it takes?I have running epochs 30,but the result is not desired ,is the file "__merged_road.jpg" the result?It seems to be wrong.

**Comment by ybarancan** [comment]
Hi,
The results are visualized in 'merged_road' yes. You can check the validation metric results to see if the training is complete. It is hard to comment on the state of the model based on a few visual examples.
