### ISSUE TITLE
what's your directory structure?

### ISSUE THREAD

**Issue by raozhongyu** [ybarancan/STSU#3]
Thanks for your great work, I'd like to konw what's your directory structure?

**Comment by raozhongyu** [comment]
Especially for your dataset.

**Comment by ybarancan** [comment]
Hi, there is no set directory structure for the project. The datasets have their canonical directory structures that should be followed for the devkits to work. Other than that, you can set the dataset root folders and the folders for the processed data in config files found in configs folder. The line data that is created by the make_nuscenes_labels.py is referred as 'line_label_root' and the object labels are saved in 'seg_label_root'. There are also associated dictionaries that are saved in 'loc_dict_path' and 'obj_dict_path'.
Cheers

**Comment by raozhongyu** [comment]
Thank's a lot.
