### ISSUE TITLE
How can you get the numerical value of the x_limit and y_limit in your code?

### ISSUE THREAD

**Issue by liuzhidemaomao** [ybarancan/STSU#5]

**Comment by ybarancan** [comment]
It is used for BEV position encoding and it is set in src/detr/position_encoding.py init function. y_limit is the max depth of the region of interest (50 meters in our paper) and we set x_limit heuristically to be larger than half x length of ROI (which is also 50 meters). So we set it to 40.  Any value above 25 in our case would work fine.
