### ISSUE TITLE
Getting BEV predictions for unseen datasets?

### ISSUE THREAD

**Issue by kevinvlowell** [ybarancan/STSU#9]
How would I go about using the model for prediction and BEV visualization on datasets that are not NuScenes or Argo?

I have a collection of front-facing camera videos that I would like to pass through the model to see the outcome, but it's not entirely clear if that is supported in the repo.

**Comment by ybarancan** [comment]
If you are going to use the pre-trained model we provide, you will need to supply some 'calib' matrix. If you don't have it you can try to give the nuscenes or argo calib matrix. Other than that, you can just resize your images and feed them. Of course without labels,, calculating metrics is not possible. You can create a copy of nuscenes or argo dataset.py file and change the image loading and calib loading. You can delete all other label etc. sub functions.
